version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGO_URL: "mongodb://mongo:27017/mydb"
      RABBITMQ_URL: "amqp://rabbitmq"

  mongo:
    image: mongo:6.0
    volumes:
      - mongo_volume:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mongo_volume: